- type: replace
  path: /releases/name=statsd-injector?
  value:
    name: statsd-injector
    version: latest

- type: replace
  path: /instance_groups/name=doppler/jobs/name=statsd_injector?
  value:
    name: statsd_injector
    release: statsd-injector
    properties:
      loggregator:
        tls:
          ca_cert: "((statsd_injector.ca))"
          statsd_injector:
            cert: "((statsd_injector.certificate))"
            key: "((statsd_injector.private_key))"

- type: replace
  path: /variables/name=statsd_injector?
  value:
    name: statsd_injector
    type: certificate
    options:
      ca: loggregator_ca
      common_name: statsdinjector
      extended_key_usage:
      - client_auth

