name: statsd-injector

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: statsd-injector
  version: latest
- name: loggregator-agent
  version: latest
- name: bpm
  version: latest

instance_groups:
- name: statsd_injector
  azs:
  - z1
  instances: 1
  persistent_disk_type: default
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: statsd_injector
    release: statsd-injector
    properties:
      statsd_injector:
        deployment: statsd-injector
      loggregator:
        tls:
          ca_cert: "((statsd_injector.ca))"
          statsd_injector:
            cert: "((statsd_injector.certificate))"
            key: "((statsd_injector.private_key))"

variables:
- name: loggregator_ca
  type: certificate
  options:
    is_ca: true
    common_name: loggregatorCA
- name: statsd_injector
  type: certificate
  options:
    ca: loggregator_ca
    common_name: statsdinjector
    extended_key_usage:
    - client_auth

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
